// <auto-generated />
using System;
using DiscountMS.Host.Domain.DbCtx;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscountMS.Host.Migrations
{
    [DbContext(typeof(DiscountServiceDbContext))]
    [Migration("20231123112718_AddedDiscountsTable")]
    partial class AddedDiscountsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.Discount", b =>
                {
                    b.Property<long>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscountId"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("DiscountAmountTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountTerminationTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("SpecificDiscountTableKey")
                        .HasColumnType("bigint");

                    b.HasKey("DiscountId");

                    b.HasIndex("DiscountAmountTypeId");

                    b.HasIndex("DiscountTerminationTypeId");

                    b.HasIndex("DiscountTypeId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.DiscountAmountType", b =>
                {
                    b.Property<int>("DiscountAmountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountAmountTypeId"));

                    b.Property<string>("DiscountAmontTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscountAmountTypeId");

                    b.ToTable("DiscountAmountTypes");

                    b.HasData(
                        new
                        {
                            DiscountAmountTypeId = 1,
                            DiscountAmontTypeName = "FixedAmount"
                        },
                        new
                        {
                            DiscountAmountTypeId = 2,
                            DiscountAmontTypeName = "Percentage"
                        });
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.DiscountTerminationType", b =>
                {
                    b.Property<int>("DiscountTerminationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountTerminationTypeId"));

                    b.Property<string>("DiscountTerminationTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscountTerminationTypeId");

                    b.ToTable("DiscountTerminationTypes");

                    b.HasData(
                        new
                        {
                            DiscountTerminationTypeId = 1,
                            DiscountTerminationTypeName = "SpecificDate"
                        },
                        new
                        {
                            DiscountTerminationTypeId = 2,
                            DiscountTerminationTypeName = "OutOfStock"
                        },
                        new
                        {
                            DiscountTerminationTypeId = 3,
                            DiscountTerminationTypeName = "Never"
                        });
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.DiscountType", b =>
                {
                    b.Property<int>("DiscountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountTypeId"));

                    b.Property<string>("DiscountTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscountTypeId");

                    b.ToTable("DiscountTypes");

                    b.HasData(
                        new
                        {
                            DiscountTypeId = 1,
                            DiscountTypeName = "Personal"
                        },
                        new
                        {
                            DiscountTypeId = 2,
                            DiscountTypeName = "InventoryItem"
                        },
                        new
                        {
                            DiscountTypeId = 3,
                            DiscountTypeName = "FromInvoiceTotal"
                        },
                        new
                        {
                            DiscountTypeId = 4,
                            DiscountTypeName = "Sale"
                        },
                        new
                        {
                            DiscountTypeId = 5,
                            DiscountTypeName = "InventoryItemBasedOnInvoiceAmount"
                        });
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.InventoryItemDiscount", b =>
                {
                    b.Property<long>("InventoryItemDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryItemDiscountId"));

                    b.Property<long>("InventoryItemId")
                        .HasColumnType("bigint");

                    b.HasKey("InventoryItemDiscountId");

                    b.ToTable("InventoryItemDiscounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.InventoryItemOnInvoiceTotalDiscount", b =>
                {
                    b.Property<long>("InventoryItemOnInvoiceTotalDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryItemOnInvoiceTotalDiscountId"));

                    b.Property<long>("InventoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InventoryItemPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.HasKey("InventoryItemOnInvoiceTotalDiscountId");

                    b.ToTable("InventoryItemOnInvoiceTotalDiscounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.InvoiceTotalDiscount", b =>
                {
                    b.Property<long>("InvoiceTotalDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InvoiceTotalDiscountId"));

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceTotalDiscountId");

                    b.ToTable("InvoiceTotalDiscounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.PersonalDiscount", b =>
                {
                    b.Property<long>("PersonalDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonalDiscountId"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PersonalDiscountId");

                    b.ToTable("PersonalDiscounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.SaleDiscount", b =>
                {
                    b.Property<long>("SaleDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SaleDiscountId"));

                    b.Property<int>("SaleTypeId")
                        .HasColumnType("integer");

                    b.HasKey("SaleDiscountId");

                    b.HasIndex("SaleTypeId");

                    b.ToTable("SaleDiscounts");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.SaleType", b =>
                {
                    b.Property<int>("SaleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SaleTypeId"));

                    b.Property<string>("SaleTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SaleTypeId");

                    b.ToTable("SaleTypes");

                    b.HasData(
                        new
                        {
                            SaleTypeId = 1,
                            SaleTypeName = "Opening"
                        },
                        new
                        {
                            SaleTypeId = 2,
                            SaleTypeName = "Seasoned"
                        },
                        new
                        {
                            SaleTypeId = 3,
                            SaleTypeName = "Holiday"
                        },
                        new
                        {
                            SaleTypeId = 4,
                            SaleTypeName = "Final"
                        });
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.Discount", b =>
                {
                    b.HasOne("DiscountMS.Host.Domain.Model.DiscountAmountType", "DiscountAmountType")
                        .WithMany()
                        .HasForeignKey("DiscountAmountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscountMS.Host.Domain.Model.DiscountTerminationType", "DiscountTerminationType")
                        .WithMany()
                        .HasForeignKey("DiscountTerminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscountMS.Host.Domain.Model.DiscountType", "DiscountType")
                        .WithMany()
                        .HasForeignKey("DiscountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountAmountType");

                    b.Navigation("DiscountTerminationType");

                    b.Navigation("DiscountType");
                });

            modelBuilder.Entity("DiscountMS.Host.Domain.Model.SaleDiscount", b =>
                {
                    b.HasOne("DiscountMS.Host.Domain.Model.SaleType", "SaleType")
                        .WithMany()
                        .HasForeignKey("SaleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleType");
                });
#pragma warning restore 612, 618
        }
    }
}
